### ISSUE TITLE
VRAMが徐々にリークします

### ISSUE THREAD

**Issue by animede** [Aivis-Project/AivisSpeech-Engine#18]
## 不具合の内容

VRAMが徐々にリークします。長文ほどリークが大きい傾向になりますが、VRAM限界まで使ってもその後は問題なく動き続けます。

### 現象・ログ

上記の結果、GPUに同居している他のAIがOOMになります。Aivis-EngineはVRAM限界でも動くので影響はありません。

### 再現手順

800字程度でエラーを生じさせると一気に消費します。

### 期待動作

リークが無い、あるいはクリアする手段があると助かります。

## AivisSpeech Engine のバージョン

1.3だったか

## OS の種類 / バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux
Ubuntu22.04-jp

**Comment by tsukumijima** [comment]
<img width="914" alt="image" src="https://github.com/user-attachments/assets/61b7aad5-e593-4ba4-81a3-731188c21e85" />

すでに閉じられているようですが、README に記載の通り、アーキテクチャ上もともと長文を入力することは想定されていないものと思われます。
適宜句読点などキリの良いタイミングで区切った上で音声合成 API にリクエストするようにしていただけますと幸いです。
